Rails.application.routes.draw do
  root 'counter#menu'
  #get 'counter/menu'
  get '/menu', to: 'counter#menu'
  #get 'counter/incr'
  get '/incr', to: 'counter#incr'
  #get 'counter/decr'
  get '/decr', to: 'counter#decr'
  #get 'counter/reset'
  get '/reset', to: 'counter#reset'
  #get 'counter/health'
  get '/health', to: 'counter#health'
  #get 'counter/metrics'
  get '/metrics', to: 'counter#metrics'
  #get 'counter/get'
  get '/get', to: 'counter#get'
  #get 'counter/crash'
  get '/crash', to: 'counter#crash'
  #get 'counter/yolo'
  get '/yolo', to: 'counter#yolo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
